CON-1176: Review Cloud Docs
R3Conclave/ccl-documentation pull request #12
Opened 2022-10-21 07:10 UTC by JohnJoser3

I have edited all the docs in this repository as per the findings in the [content audit](https://jor3cev-my.sharepoint.com/:x:/r/personal/john_jose_r3_com/_layouts/15/Doc.aspx?sourcedoc=%7B8672C637-DFE0-49F5-B3FA-9F2BDCB49624%7D&file=Conclave-%20Content%20Audit%20v2.0.xlsb.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=john.jose%40r3.com&ct=1666335906647&wdOrigin=OFFICECOM-WEB.START.REC&cid=b12895d2-2979-4eba-9f4a-55834b6427d5). Main focus of this set of changes is to improve clarity, simplicity, and usability of the docs. Also, I have corrected a few errors and updated outdated references. The PR reference number CON-1176 refers to [this ticket](https://r3-cev.atlassian.net/browse/CON-1176?atlOrigin=eyJpIjoiNWRkZDhmMmZjMGY2NGIxMGI2M2YwOTJhYThlNmQwZTgiLCJwIjoiaiJ9) raised in the Conclave Core Jira board.

2022-12-08 14:40 UTC, roy-hopkins requested changes
Really good changes! I've highlighted a couple of things to address, otherwise it looks fantastic!

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/conclavepass-sample.md
> +The functions component consists of a typescript that provides methods that you can use to add, query, get,
"a typescript that..." doesn't read correctly. Maybe "a typescript module that..."

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/conclavepass-sample.md
> +The backend service needs to be available as a fixed IP on the internet to allow Conclave Functions to access it for
"available with a fixed IP address on the internet."

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/conclavepass-sample.md
> +choose a VM with the smallest size, as the resource requirements are less.
"the resource requirements are minimal".

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/index.md
> +Use the resources below to use the platform.
This doesn't read clearly with 'use' twice.

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/index.md
> +    1. Download the `ccl` tool using [this link](https://github.com/R3Conclave/ccl-documentation/releases/download/1.0.0-beta2/ccl).
Can we add another step here?
`chmod +x ccl` to make the tool executable.

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/index.md
> +1. Download and unzip [the SDK](https://github.com/R3Conclave/ccl-documentation/releases/download/1.0.0-beta2/conclave-cloud-sdk-java-1.0.0-beta2.zip)
I think this link is now out of date - shouldn't be `beta2`. 
https://github.com/R3Conclave/ccl-documentation/releases/download/1.0.0-GA/conclave-cloud-sdk-java-1.0.0-GA.zip

2022-12-08 14:40 UTC, roy-hopkins commented on user-guide/docs/what-is-conclave-cloud.md
> +![An architecture diagram of the proposed Conclave CLoud ecosystem](assets/ImmersiveEcosystem-CCL.drawio.png)
Capital L in "Conclave CLoud" in the link name.

2022-12-12 09:20 UTC, JohnJoser3 commented
Fixed the review comments. Please take a look.

2022-12-15 09:04 UTC, roy-hopkins approved these changes
Excellent improvements! Sorry the review took so long.

2022-12-15 09:18 UTC, merged